### ISSUE TITLE
Combine Audio Settings to Single Control

### ISSUE THREAD

**Issue by iamwally** [ShadowLight8/Dynamic_RDS#3]

**Comment by ShadowLight8** [comment]
Combine the Input Impedance, Digital Gain, and Buffer Gain into a single Gain control. All possible combinations will still be present, just simplified with a single volume-like gain value.

**Comment by ShadowLight8** [comment]
Determined that some combinations of the above items result in duplicate values, so not all combinations are needed. Condensed down to a single -15 to +20 gain adjustment.
