### ISSUE TITLE
Add ability to change the PS and RT style texts either through script or add FPP command (better option)

### ISSUE THREAD

**Issue by chrkov** [ShadowLight8/Dynamic_RDS#32]
If possible, I think it would be great if we can change the PS and RT style texts through either a script or, a better option, an FPP command addition.

Basically, I would like to display song information and other related information during a show.   But when show is not running, be able to display different information, like what time the next show starts.

Right now, the only way to do it is static in the configuration page and it requires a restart of FPP to update.

**Comment by ShadowLight8** [comment]
I like this idea! Not sure exactly how to do it yet, but I'll figure it out 👍

**Comment by ShadowLight8** [comment]
I found this can be done with a small script using curl, the FPP api, and the Dynamic_RDS live update feature:

```
#!/bin/bash
curl -d 'Merry|Christ-|  -mas!|{T}|{A}|[{N} of {C}]' -X POST http://localhost/api/plugin/Dynamic_RDS/settings/DynRDSPSStyle
curl -d 'Merry Christmas! {T}[ by {A}]|[Track {N} of {C}]' -X POST http://localhost/api/plugin/Dynamic_RDS/settings/DynRDSRTStyle
curl http://localhost/api/plugin/Dynamic_RDS/FastUpdate
```

The single quotes around the style text in the script is important so the Linux shell (bash) won't try to interpret what is in there.
You can save this into a file (rds_text_change.sh or anything you like) in the media/scripts folder and then use it with the scheduler (via Command -> Run Script) or playlists.

@chrkov Let me know how it goes!

**Comment by chrkov** [comment]
Verified!  Works just as you said.  Nice work on everything.   This plugin is going to be huge!

You Rock!

**Comment by ShadowLight8** [comment]
Hey Christopher! @chrkov 
That's great. I was a bit surprised that everything was already there, it just took gluing it together. In PR #43, I've added a new section with this scripting example. Thanks for the great suggestion and testing it out. I'll close this item out when I push to main shortly.

**Comment by ShadowLight8** [comment]
@chrkov That would be great!

**Comment by chrkov** [comment]
Lets see if I can just paste this.   This is what I used.  Just update variables then.

#!/bin/bash
###########################################################
# RDS_Default.sh - Used to change the PS and/or RT RDS Strings         #
###########################################################

# Set the PS text (set to '' or comment out to leave unchanged)
PS='Merry|Christ-|  -mas!|{T}|{A}|[{N} of {C}]'

# Set the RT text
RT='Merry Christmas! {T}[ by {A}]|[Track {N} of {C}]'

if [ "$PS" != "" ]; then
echo 'Setting PS Style Text to: '$PS
curl -d "$PS" -X POST http://localhost/api/plugin/Dynamic_RDS/settings/DynRDSPSStyle
echo -e '\n'
fi

if [ "$RT" != "" ]; then
echo 'Setting RT Style Text to: '$RT
curl -d "$RT" -X POST http://localhost/api/plugin/Dynamic_RDS/settings/DynRDSRTStyle
fi

echo -e  '\nApplying changes'

curl http://localhost/api/plugin/Dynamic_RDS/FastUpdate

echo 'Complete'

**Comment by chrkov** [comment]
Took me a couple paste trials to figure out how to keep the code in tack but finally got it.   I suck at this github stuff....  Getting better though...
