### ISSUE TITLE
PI Code information update

### ISSUE THREAD

**Issue by chrkov** [ShadowLight8/Dynamic_RDS#33]
Just an FYI.   Under the help for the PI CODE you list two websites and one doesn't seem to work.  http://audemat-radio.com/popup/picode.php (also tried  http://audematradio.com/popup/picode.php) seems to be a dead link.

I found a replacement of https://caseymediallc.com/rdsreverse

**Comment by ShadowLight8** [comment]
@chrkov Nice catch! I've made the change in my next branch #34, but will keep this open until merged.
