### ISSUE TITLE
Reduce FPP Restart For Settings Changes

### ISSUE THREAD

**Issue by iamwally** [ShadowLight8/Dynamic_RDS#4]

**Comment by ShadowLight8** [comment]
When changing a setting that can be dynamically updated on the transmitter, find a way to make that happen rather than having to restart FPP all the time.

**Comment by ShadowLight8** [comment]
Might be able to use similar logic to https://github.com/ShadowLight8/Si4713_FM_RDS/blob/master/plugin_setup.php#L42 to trigger a reload.

**Comment by ShadowLight8** [comment]
Working for audio settings. Looking to see if other settings should be able to be changed on the fly as well. Otherwise, doing a bit more testing before closing this out.

**Comment by ShadowLight8** [comment]
In my testing, I've not found any other settings that need or make sense to be changed live. The mechanism is in place and it's quick to add other settings. We can open a new issue if needed for other settings.
