### ISSUE TITLE
Investigate using lifecycle events from FPP

### ISSUE THREAD

**Issue by ShadowLight8** [ShadowLight8/Dynamic_RDS#45]
I learned that plugins can register for the FPP lifecycle events of "start" and "shutdown". A restart is a "shutdown" followed quickly by a "start".

The "start" event is already covered by the "list" call to callback.py, so nothing new would be needed.

The "shutdown" event would be new code to allow for a clean shutdown of the engine. Mostly this will ensure that hardwarePWM is stopped and softwarePWM is set to a low state. Currently, when FPP stops, it kills child processes (like engine.py), so PWM can be left in an unexpected state (such as the transmitter being on at full power, which gets very HOT).

This means the engine.py will start, shutdown, and restart along side of FPP. Whereas today, it doesn't quite do that (especially around restarts).

@iamwally @chrkov @ThomasRa1 - Any concerns with this change?

**Comment by iamwally** [comment]
No actually that seems better and how it should be to me😎
John Maugeri
***@***.***
 

    On Sunday, January 28, 2024 at 09:59:28 AM EST, Nick Anderson ***@***.***> wrote:  
 
 


I learned that plugins can register for the FPP lifecycle events of "start" and "shutdown". A restart is a "shutdown" followed quickly by a "start".

The "start" event is already covered by the "list" call to callback.py, so nothing new would be needed.

The "shutdown" event would be new code to allow for a clean shutdown of the engine. Mostly this will ensure that hardwarePWM is stopped and softwarePWM is set to a low state. Currently, when FPP stops, it kills child processes (like engine.py), so PWM can be left in an unexpected state (such as the transmitter being on at full power, which gets very HOT).

This means the engine.py will start, shutdown, and restart along side of FPP. Whereas today, it doesn't quite do that (especially around restarts).

@iamwally @chrkov @thomasra1 - Any concerns with this change?

**Comment by chrkov** [comment]
I agree.   This sounds like the way it should run.
