### ISSUE TITLE
Add support for BBB

### ISSUE THREAD

**Issue by iamwally** [ShadowLight8/Dynamic_RDS#5]

**Comment by ShadowLight8** [comment]
Look into changes needed around python and hardware specific code

**Comment by ShadowLight8** [comment]
Removed platform restriction in 9615ce9c4024da1a5d8566d09e442b9b9c6295f2 to start BBB testing. Support not expected yet

**Comment by ShadowLight8** [comment]
Commit af6afb67cecb7f81bb2bb7057669318fd5782e4e switches to os.path.exists instead of os.path.isfile or os.path.isdir to detect i2c buses on BBB.

**Comment by ShadowLight8** [comment]
See https://github.com/FalconChristmas/fpp/issues/1322
Will try adding a workaround to the fpp_install.sh script to check for and create the python -> python3 symlink if needed

**Comment by ShadowLight8** [comment]
https://github.com/FalconChristmas/fpp/issues/1322 has been closed with eventScript being updated to use python3

**Comment by AGFazio** [comment]
Do you a pinout location of where to hookup the wires for the BBB?

**Comment by chrkov** [comment]
Can you tell me where the PWM connects on the BBB?   I have the gnd, sda and scl figured out, but cant figure out where the PWM is suppose to go.

**Comment by ShadowLight8** [comment]
I've not completed the code for BBB's PWM, but it would likely go to P9-14 (PWM1A) or 16 (PWM1B)

**Comment by ShadowLight8** [comment]
Started #44

**Comment by ShadowLight8** [comment]
Most of the functionality has been added to #44. Starting to do some long running tests. When PWM is enabled on the BBB it seems to interfere with I2C more than what is seen on the RPi. Haven't tried more shielding yet.
