### ISSUE TITLE
Transmit Frequency Increments Incorrectly

### ISSUE THREAD

**Issue by iamwally** [ShadowLight8/Dynamic_RDS#8]
Transmitter frequency increments by whole numbers

**Comment by ShadowLight8** [comment]
Value can by typed in, but the up/down arrows are whole numbers only. Confirmed that settings.json has step=0.05 defined. HTML of the plugin config page does not have the step attribute defined.

**Comment by ShadowLight8** [comment]
Opened https://github.com/FalconChristmas/fpp/pull/1310 with a fix to common.php to include the step when needed. Waiting for PR to be merged.

**Comment by ShadowLight8** [comment]
PR was merged. I'm going to close this since there isn't any more to change, but the issue will still exist until the fix is included in a future fpp version.
